### ISSUE TITLE
One true parent module

### ISSUE THREAD

**Issue by doismellburning** [BrewPi/connector#8]
Currently there's 8 modules in the top level of this repo

I suspect they would do well to belong under a parent `connector` module (or at the very least a `src` dir)

Before I spend an age fiddling with imports - thoughts? Opinions?

**Comment by doismellburning** [comment]
(It would also make `coverage` / `flake8` targeting easier)

**Comment by m-mcgowan** [comment]
I'm refactoring this repo to split out the non-brewpi specifics - I'll place everything under a connector package. 

What's the usual layout for a python project? Are sources usually under src? I also have some resources, e.g. configuration files that are used for the integration tests - where's the best place for these.

**Comment by m-mcgowan** [comment]
For now, we have everything under `brewpi`, with tests under a subpackage. I'm still unsure about that, but if we decide to change it we can open a new issue. Closing this one out now that we have a single top level package.
